[toolchain]
solana = "1.17.25"
anchor = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
mushi_program = "HF5x1bCgynzEnBL7ATMFYPNFjBaqfxgMASyUJL2ud6Xi"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Devnet"
#cluster = "https://solana-devnet.g.alchemy.com/v2/RriT8QaP5dWpHS1DH-2Vr5UTm3-xN_Lm"
cluster = "https://devnet.helius-rpc.com/?api-key=740627da-3f16-4e0e-9ef2-27ad1d79ea54"
#cluster = "https://solana-devnet.drpc.org"
#cluster = "https://endpoints.omniatech.io/v1/sol/devnet/public"
#cluster = "https://devnet.helius-rpc.com/?api-key=b2a1042e-4c63-4c37-9241-d02b4e5ee0fa"
#cluster = "https://rpc.ankr.com/solana_devnet/3cd79961b0f2d441be4717faeafc0fca9816cb0e0d6c357fb6b8f25dfd42736a"
wallet = "/root/.config/solana/id.json"

[scripts]
borrow = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/borrow.ts"
borrowMore = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/borrow_more.ts"
buy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/buy.ts"
buyReferral = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/buy_referral.ts"
closePosition = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/close_position.ts"
extendLoan = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/extend_loan.ts"
flashClose = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/flash_close_position.ts"
getStats = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/getStats.ts"
init = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/init.ts"
leverage = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/leverage.ts"
removeCollateral = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/remove_collateral.ts"
repay = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/repay.ts"
sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/sell.ts"
start = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/start.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
setStakeToken = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/setStakeToken.ts"
updateFeeReceiver = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/updateFeeReceiver.ts"
stake = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/stake.ts"
unstake = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/unstake.ts"
keygen = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/keygen.ts"
liquidate = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/liquidate.ts"
