[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mushi_program = "HF5x1bCgynzEnBL7ATMFYPNFjBaqfxgMASyUJL2ud6Xi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
buy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/buy.ts"
init = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/init.ts"
sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/sell.ts"
start = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/start.ts"
getStats = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/getStats.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
updateAdmin = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/updateAdmin.ts"
updateFeeReceiver = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/updateFeeReceiver.ts"
