[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
eggs = "2vLjCSQp3vGJj2kqh5CHdn5LrvfXWiANrjq1a2NDUPUY"

[programs.localnet]
eggs = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
