[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mushi_program = "65zNCEhvCtWo6DcphN6omP5Cz3hFo6zjUkHZfEauMDXr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
init = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/init.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
updateAdmin = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/updateAdmin.ts"
updateFeeReceiver = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/updateFeeReceiver.ts"
